### ISSUE TITLE
ravshello assumes that 2 blueprints cannot have the same name ("already used by a sibling" returned when trying to list blueprints)

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#108]
```
[ablum@badger ~]$ ravshello -a '/blueprints refresh'
Welcome to ravshello, a shell to provision & manage machines with Ravello!

Determining nickname . . .
  (Nickname will be prepended to names of any apps you create)
  (Nickname will be used to restrict which app names you can see)
  Using system user 'ablum' for nickname

Connecting to Ravello . . .
  Logged in to Ravello as ADMIN
  Fetching data from Ravello . . . Done!


Refreshing all blueprint data . . . Traceback (most recent call last):
  File "/home/ablum/bin/ravshello", line 186, in <module>
    main()
  File "/home/ablum/bin/ravshello", line 181, in main
    user_interface.main(rOpt, rClient)
  File "/home/ablum/git/ravshello/user_interface.py", line 128, in main
    shell.run_cmdline(rOpt.cmdlineArgs)
  File "/home/ablum/git/ravshello/configshell_fb/shell.py", line 890, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/home/ablum/git/ravshello/configshell_fb/shell.py", line 865, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/home/ablum/git/ravshello/configshell_fb/node.py", line 1413, in execute_command
    return method(*pparams, **kparams)
  File "/home/ablum/git/ravshello/user_interface.py", line 1191, in ui_command_refresh
    self.refresh()
  File "/home/ablum/git/ravshello/user_interface.py", line 1176, in refresh
    Bp("%s" % bp['name'], self, bp['id'], bp['creationTime'])
  File "/home/ablum/git/ravshello/user_interface.py", line 1392, in __init__
    ConfigNode.__init__(self, name, parent)
  File "/home/ablum/git/ravshello/configshell_fb/node.py", line 104, in __init__
    % self._name)
ValueError: Name 'RH342-20160226-dev-bp' already used by a sibling.
```

Not sure if that's a naming issue on the account side or what...

**Comment by ryran** [comment]
@ajblum Hit me up in IRC about this. I can't see this issue on the 3 accounts I have access to.

**Comment by ryran** [comment]
So to give a clear example that you can take to Ravello support: y'all have TWO blueprints on your account with the same name: `CL310-RHELOSP60-1.r33436-bp`. One has id `62457215` (that's the one originally shared by Robert Locke) and the other (owned by Andrew Blum) has id `66158659`.

When you login to the WebUI you can only see the latter one owned by Andrew Blum, but using the API, you can see both. I'm guessing this is a recent change Ravello has made that has something to do with shares.

**Comment by ryran** [comment]
Work-around leads to this:

```
/blueprints> ls
o- blueprints .......................................... [595 blueprints, 123 tagged for learners]
  <OUTPUT TRUNCATED>
  o- zz___CEPH125-20160114-bp___id67437845 .................. [Rudolf Kastl created on 2016/01/14]
  o- zz___CEPH125-20160114-bp___id67437878 ................... [Andrew Blum created on 2016/01/14]
  o- zz___CL310-RHELOSP60-1.r33436-bp___id62457215 .......... [Robert Locke created on 2015/09/06]
  o- zz___CL310-RHELOSP60-1.r33436-bp___id66158659 ........... [Andrew Blum created on 2015/11/30]
  o- zz___DO407-20160502-dev-bp___id70648061 ............... [Scott McBrien created on 2016/05/02]
  o- zz___DO407-20160502-dev-bp___id71074266 ................. [Andrew Blum created on 2016/05/06]
  o- zz___RH236-RHSTOR30-1.r33684-bp-rhu___id64520215 . [Eric Schwarzweller created on 2015/11/03]
  o- zz___RH236-RHSTOR30-1.r33684-bp-rhu___id67864079 ........ [Andrew Blum created on 2016/01/28]
  o- zz___RH342-20160226-dev-bp___id68715053 ............... [Scott McBrien created on 2016/02/26]
  o- zz___RH342-20160226-dev-bp___id69076066 ................. [Andrew Blum created on 2016/03/10]
  o- zz___gss-st02-0253___id68157978 .......... [GSS Training Admin Account created on 2016/02/02]
  o- zz___gss-st02-0253___id68157981 ......................... [Andrew Blum created on 2016/02/02]
/blueprints> 
```

..but as my above comment implied, this is definitely something on the Ravello side -- we need guidance from them on what the heck happened and why.

**Comment by ryran** [comment]
Fixed. See  #113 for further details.
