### ISSUE TITLE
connection timeouts

### ISSUE THREAD

**Issue by THEdoubleh** [ryran/ravshello#12]
The upstream Ravello python-sdk recently switched what module they use for handling the http connections to Ravello. (It was [pull request #7](https://github.com/ravello/python-sdk/pull/7).)

In ravshello we instantiate one `RavelloClient()` object and login only once and then use that for all API calls until ravshello exits. It seems that something about the new code (which uses `requests` instead of `httplib`) is leading to almost-immediate timeouts.

Today Hayley was logged in to the old version from the morning all the way until 4 in the afternoon, doing commands sporadically (every hour or so). No problems. That's typical. Occasionally a command fails (not even once a day I think) but simply trying the same command again always succeeds. There's never a need to quit and login again.

After switching to the new version around 4pm, it became pretty clear that something big was different -- within minutes of inactivity she got the following traceback and had to quit out of ravshello to login again. 

```
/apps/GSS-Satellite-Readiness-6.0-Module4-latest-v9_0> query_app_status 

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 948, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 778, in _cli_loop
    if self._save_history:
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 892, in run_cmdline
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 867, in _execute_command
    self.log.debug("Command execution returned %r" % result)
  File "./ravshello/out00-PYZ.pyz/configshell.node", line 1417, in execute_command
  File "./ravshello/out00-PYZ.pyz/user_interface", line 1926, in ui_command_query_app_status
  File "./ravshello/out00-PYZ.pyz/user_interface", line 1930, in query_app_status
  File "./ravshello/out00-PYZ.pyz/user_interface", line 341, in get_application_details
  File "./ravshello/out00-PYZ.pyz/ravello_sdk", line 447, in get_application
  File "./ravshello/out00-PYZ.pyz/ravello_sdk", line 325, in request
  File "./ravshello/out00-PYZ.pyz/ravello_sdk", line 386, in _request
RavelloError: got status 401 (unknown/unknown)
```

**Comment by ryran** [comment]
@THEdoubleh : I'm gonna track my work here but I'm not expecting you to read any of this. I'll let you know the end result. :)

**Comment by ryran** [comment]
*(Seeking guidance from Ravello devs on upstream sdk in https://github.com/ravello/python-sdk/issues/12)*
