### ISSUE TITLE
fix all recently-broken /apps/APP/vms/VM commands

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#125]
```
/apps/dev2> vms/EX-host5 start 
Traceback (most recent call last):
  File "/home/rsaw/bin/ravshello", line 176, in <module>
    main()
  File "/home/rsaw/bin/ravshello", line 171, in main
    user_interface.main()
  File "/g/ravshello/modules/user_interface.py", line 148, in main
    shell.run_interactive(exit_on_error=rOpt.enableDebugging)
  File "/g/ravshello/modules/configshell_fb/shell.py", line 904, in run_interactive
    self._cli_loop()
  File "/g/ravshello/modules/configshell_fb/shell.py", line 733, in _cli_loop
    self.run_cmdline(cmdline)
  File "/g/ravshello/modules/configshell_fb/shell.py", line 847, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/g/ravshello/modules/configshell_fb/shell.py", line 822, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/g/ravshello/modules/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/g/ravshello/modules/user_interface.py", line 2442, in ui_command_start
    if not rootNode.get_child('apps').confirm_app_is_published():
AttributeError: 'Applications' object has no attribute 'confirm_app_is_published'
```

**Comment by ryran** [comment]
WHOOPS. Fixed.
