### ISSUE TITLE
keyerror: 'name' when interface name is missing

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#161]
If a blueprint is built with any VM NOT having a name filled in for the an interface name, ravshello will fail to list connection details when running `query_status`  here is what I see when in debug:

```
/apps> GSS-CL02-1502-qa-bp_0/ query_status 
Running command line 'GSS-CL02-1502-qa-bp_0/ query_status'.

App VMs in region US-East-1 will auto-stop in 117:49 min at 15:14:09

  docker.example.com
     State:              STARTING
     Internal DNS Name:  docker.example.com
Traceback (most recent call last):
  File "/home/ablum/bin/ravshello", line 272, in <module>
    main()
  File "/home/ablum/bin/ravshello", line 267, in main
    user_interface.main()
  File "/home/ablum/.local/share/ravshello/modules/user_interface.py", line 193, in main
    shell.run_interactive(exit_on_error=rOpt.enableDebugging)
  File "/home/ablum/.local/share/ravshello/modules/configshell_fb/shell.py", line 904, in run_interactive
    self._cli_loop()
  File "/home/ablum/.local/share/ravshello/modules/configshell_fb/shell.py", line 733, in _cli_loop
    self.run_cmdline(cmdline)
  File "/home/ablum/.local/share/ravshello/modules/configshell_fb/shell.py", line 847, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/home/ablum/.local/share/ravshello/modules/configshell_fb/shell.py", line 822, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/home/ablum/.local/share/ravshello/modules/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/home/ablum/.local/share/ravshello/modules/user_interface.py", line 1875, in ui_command_query_status
    self.query_status()
  File "/home/ablum/.local/share/ravshello/modules/user_interface.py", line 1991, in query_status
    print("     NIC {}".format(nic['name']))
KeyError: 'name'
```
Of course, blueprints **should** have named interfaces, but I would hope that if 'name' is null then just leave it off and just call it "NIC" as opposed to "NIC eth0".

**Comment by ryran** [comment]
Ahh my bad for not even considering that it was possible to have a null in that field.

**Comment by ryran** [comment]
@ajblum 

Fixed in next release. Looks like:

```
  VMNAME
     State:            STOPPED
     Hostnames:        somehostname
     NIC (no name)
       Internal IP:    172.16.1.1
```

**Comment by ryran** [comment]
PS: The `/apps/<APP>/vms/<VM>/ query_status` command heavily depends on the existence of `nic['name'] ... so I'm not even bothering to mess with that.
