### ISSUE TITLE
query_status reports `'ipConfig'` KeyError after network editing change

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#191]
Since the network editing change, query_status reports the following failure:

```
/apps/hack-the-stack-2016-W39_0> query_status 
Running command line 'query_status'.

App VMs in region US-Central-1 will auto-stop in 116:51 min at 11:56:02

Traceback (most recent call last):
  File "/usr/bin/ravshello", line 319, in <module>
    main()
  File "/usr/bin/ravshello", line 314, in main
    user_interface.main()
  File "/usr/share/ravshello/modules/user_interface.py", line 214, in main
    shell.run_interactive(exit_on_error=rOpt.enableDebugging)
  File "/usr/share/ravshello/modules/configshell_fb/shell.py", line 904, in run_interactive
    self._cli_loop()
  File "/usr/share/ravshello/modules/configshell_fb/shell.py", line 733, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/share/ravshello/modules/configshell_fb/shell.py", line 847, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/share/ravshello/modules/configshell_fb/shell.py", line 822, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/share/ravshello/modules/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/usr/share/ravshello/modules/user_interface.py", line 2134, in ui_command_query_status
    self.query_status(app)
  File "/usr/share/ravshello/modules/user_interface.py", line 2170, in query_status
    out = get_vm_access_details(vm)[0]
  File "/usr/share/ravshello/modules/user_interface.py", line 290, in get_vm_access_details
    if 'autoIpConfig' in nic['ipConfig']:
KeyError: 'ipConfig'
```

**Comment by ajblum** [comment]
```
[root@somehost.example.com ~]# ravshello -V
ravshello v1.35.0 last mod 2017/09/26
```

**Comment by ajblum** [comment]
printing the nic json object just before 290 for this app revels:

```
{
    "device": {
        "generatedMac": "2c:c2:60:36:d6:e9",
        "index": 0,
        "mac": "2c:c2:60:36:d6:e9",
        "deviceType": "virtio",
        "useAutomaticMac": false
    },
    "vlanInterfaces": [
        {
            "vlanId": 100,
            "id": 3291756059306500096,
            "ipConfigurations": [
                {
                    "needElasticIp": false,
                    "hasPublicIp": false,
                    "publicIp": "35.193.120.119",
                    "externalAccessState": "CONDITIONAL_PUBLIC_IP",
                    "staticIpConfig": {
                        "ip": "10.20.20.25",
                        "mask": "255.255.255.0"
                    },
                    "id": 7130576188342272
                }
            ]
        },
        {
            "id": 5124028201519261696,
            "vlanId": 201
        },
        {
            "id": 3796321913275383808,
            "vlanId": 202
        },
        {
            "id": 5505263906035484672,
            "vlanId": 203
        },
        {
            "id": 9087184809504028672,
            "vlanId": 204
        }
    ],
    "id": 4304148208025600,
    "name": "eth0"
}
```
