### ISSUE TITLE
backtrace while trying to delete_app

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#23]
While logged in as an admin, I tried to delete this app:

/apps/GSS-RHOSP-Troubleshooting-Havana_0> delete_app 

Traceback (most recent call last):
  File "/home/ablum/bin/ravshello", line 184, in <module>
    main()
  File "/home/ablum/bin/ravshello", line 179, in main
    user_interface.main(rOpt, rClient)
  File "/home/ablum/ravshello/user_interface.py", line 140, in main
    shell.run_interactive()
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 948, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 777, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 891, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 866, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell/node.py", line 1413, in execute_command
    return method(*pparams, **kparams)
  File "/home/ablum/ravshello/user_interface.py", line 1777, in ui_command_delete_app
    c.slow_print(c.RED("Deleting an application cannot be undone -- All VM data will be lost\n"))
  File "/home/ablum/ravshello/string_ops.py", line 27, in slow_print
    stdout.flush()
NameError: global name 'stdout' is not defined

[ablum@badger ~]$ ravshello -V
ravshello v1.3.0-dev last mod 2015/01/21

**Comment by ajblum** [comment]
I've got the app definition saved, but I don't see a way to attach a file to this issue.

Let me know if you'd like for me to send you the app definition file.
--
Andrew

**Comment by ajblum** [comment]
[ablum@badger bin]$ cat /etc/redhat-release 
Fedora release 21 (Twenty One)
[ablum@badger bin]$ python -V
Python 2.7.8

**Comment by ryran** [comment]
Nah, unrelated to app. Can see from traceback what needs fixing. Thanks for
reporting. Be in late today.

**Comment by ajblum** [comment]
confirmed. thanks !
