### ISSUE TITLE
ittermittent ls failures with 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#32]
This doesn't happen in every session, but when it does, it continues that way for the whole session. Happens in learner and admin mode. Currently debugging.

```
[rsaw:ravshello]$ ravshello -qa ls
Welcome to ravshello, a shell to provision & manage machines with Ravello!
  Using configfile-specified nick 'rsawhill' for nickname
  Logged in to Ravello as ADMIN
Traceback (most recent call last):
  File "/home/rsaw/bin/ravshello", line 187, in <module>
    main()
  File "/home/rsaw/bin/ravshello", line 182, in main
    user_interface.main(rOpt, rClient)
  File "/home/rsaw/gitprojs/ravshello/user_interface.py", line 105, in main
    shell.run_cmdline(rOpt.cmdlineArgs)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/shell.py", line 890, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/shell.py", line 865, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/node.py", line 1413, in execute_command
    return method(*pparams, **kparams)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/node.py", line 712, in ui_command_ls
    tree = self._render_tree(target, depth=depth)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/node.py", line 863, in _render_tree
    + self._render_tree(children[i], margin, depth)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/node.py", line 863, in _render_tree
    + self._render_tree(children[i], margin, depth)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/node.py", line 863, in _render_tree
    + self._render_tree(children[i], margin, depth)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/node.py", line 863, in _render_tree
    + self._render_tree(children[i], margin, depth)
  File "/home/rsaw/gitprojs/ravshello/configshell_fb/node.py", line 767, in _render_tree
    (description, is_healthy) = root.summary()
TypeError: 'NoneType' object is not iterable
```

**Comment by ryran** [comment]
Caused by SDK bug. Ref: https://github.com/ravello/python-sdk/issues/21

**Comment by ryran** [comment]
I'm gonna close this, because we've fixed this particular issue ... despite the fact that the root cause of this has not been addressed and could potentially cause issues elsewhere....
