### ISSUE TITLE
interactive cd (cd cmd with no args) fails with "No module named urwid" error

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#55]
Whaaat? Will look into this later.

```
╰─>$ ravshello -q
Welcome to ravshello, a shell to provision & manage machines with Ravello!
  Using configfile-specified nick 'rsawhill' for nickname
  Logged in to Ravello as LEARNER

/> cd
No module named urwid
/> 
```

With debug:

```
╰─>$ ravshello -qd
Welcome to ravshello, a shell to provision & manage machines with Ravello!
  Using configfile-specified nick 'rsawhill' for nickname
  Logged in to Ravello as LEARNER

/> cd
Traceback (most recent call last):
  File "/home/rsaw/bin/ravshello", line 186, in <module>
    main()
  File "/home/rsaw/bin/ravshello", line 181, in main
    user_interface.main(rOpt, rClient)
  File "/g/ravshello/user_interface.py", line 164, in main
    shell.run_interactive(exit_on_error=rOpt.enableDebugging)
  File "/g/ravshello/configshell_fb/shell.py", line 947, in run_interactive
    self._cli_loop()
  File "/g/ravshello/configshell_fb/shell.py", line 776, in _cli_loop
    self.run_cmdline(cmdline)
  File "/g/ravshello/configshell_fb/shell.py", line 890, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/g/ravshello/configshell_fb/shell.py", line 865, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/g/ravshello/configshell_fb/node.py", line 1413, in execute_command
    return method(*pparams, **kparams)
  File "/g/ravshello/configshell_fb/node.py", line 1030, in ui_command_cd
    selected = self._lines_walker(lines, start_pos=start_pos)
  File "/g/ravshello/configshell_fb/node.py", line 1064, in _lines_walker
    import urwid
ImportError: No module named urwid
```

**Comment by ryran** [comment]
This can be fixed by simply making sure `python-urwid` (RHEL7/Fedora) is installed. Will add to dependency-checking script.
