### ISSUE TITLE
Command "/users invite_new_user" fails

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#6]
```
/apps> /users invite_new_user 

Enter details of new user you'd like to invite . . .

Email: ryan@b19.org

First name: Ryan

Last name: Saw

Problem inviting user
!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 948, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 778, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 892, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 867, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell/node.py", line 1417, in execute_command
    result = method(*pparams, **kparams)
  File "/pyi/source/user_interface.py", line 1059, in ui_command_invite_new_user
    user = ravClient.create_user(req)
  File "/pyi/source/ravello_sdk.py", line 770, in create_user
    return self.request('POST', '/users', user)
  File "/pyi/source/ravello_sdk.py", line 325, in request
    response = self._request(method, path, body, headers)
  File "/pyi/source/ravello_sdk.py", line 386, in _request
    raise RavelloError('got status {0} ({1}/{2})' .format(status, code, msg))
RavelloError: got status 405 (unknown/unknown)
```

**Comment by ryran** [comment]
https://github.com/ravello/python-sdk/issues/19

Fixed. Update your SDK, e.g.:

```
cd /your/ravshello/dir
wget -N https://raw.githubusercontent.com/ryran/python-sdk/experimental/lib/ravello_sdk.py
```
